/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_runs_get"];
        put?: never;
        /** Submit */
        post: operations["submit_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run */
        get: operations["run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Citation */
        Citation: {
            /** Path */
            path: string;
            /** Start Line */
            start_line: number;
            /** End Line */
            end_line: number;
        };
        /**
         * Evidence
         * @description Process fields are observed; text and observations remain untrusted claims.
         */
        Evidence: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "command" | "probe";
            /** Command */
            command: string;
            /** Exit Code */
            exit_code: number | null;
            /**
             * Stdout
             * @default
             */
            stdout: string;
            /**
             * Stderr
             * @default
             */
            stderr: string;
            /**
             * Timed Out
             * @default false
             */
            timed_out: boolean;
            /**
             * Output Truncated
             * @default false
             */
            output_truncated: boolean;
            /** Sandbox Id */
            sandbox_id: string;
            /** Source Digest */
            source_digest: string;
            /** Observations */
            observations?: {
                [key: string]: boolean | string | number | null;
            };
        };
        /** Finding */
        Finding: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Repo Url */
            repo_url: string;
            /**
             * Revision
             * @default HEAD
             */
            revision: string;
            /**
             * Source Mode
             * @default git_revision
             * @enum {string}
             */
            source_mode: "git_revision" | "working_snapshot";
            /** File Path */
            file_path?: string | null;
            /** Cwe */
            cwe?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvestigationResult */
        InvestigationResult: {
            finding: components["schemas"]["Finding"];
            verdict: components["schemas"]["Verdict"];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Source Digest */
            source_digest: string;
            /** Model */
            model: string;
            worker_identity?: components["schemas"]["WorkerIdentity"] | null;
            /** Usage */
            usage?: {
                [key: string]: number | null;
            };
            /** Limitations */
            limitations?: string[];
        };
        /** RunPage */
        RunPage: {
            /** Items */
            items: components["schemas"]["RunSummary"][];
            /** Next Page Token */
            next_page_token?: string | null;
        };
        /** RunState */
        RunState: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed" | "cancelled";
            /** Phase */
            phase: string;
            finding: components["schemas"]["Finding"];
            result?: components["schemas"]["InvestigationResult"] | null;
            /** Error */
            error?: string | null;
        };
        /** RunSummary */
        RunSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Closed At */
            closed_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Verdict */
        Verdict: {
            /**
             * Label
             * @enum {string}
             */
            label: "potentially_exploitable" | "likely_not_exploitable" | "inconclusive";
            /** Summary */
            summary: string;
            /** Evidence Ids */
            evidence_ids?: string[];
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /** Superseded Evidence Ids */
            superseded_evidence_ids?: string[];
        };
        /** WorkerIdentity */
        WorkerIdentity: {
            /** Fingerprint */
            fingerprint: string;
            /** Code Sha256 */
            code_sha256: string;
            /** Config Sha256 */
            config_sha256: string;
            /** Dependencies */
            dependencies: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    runs_api_runs_get: {
        parameters: {
            query?: {
                page_token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Finding"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
