/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/run-page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Page */
        get: operations["run_page_api_run_page_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiment Detail */
        get: operations["experiment_detail_api_experiments__experiment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Batches */
        get: operations["batches_api_batches_get"];
        put?: never;
        /** Submit */
        post: operations["submit_api_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/ado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Ado */
        post: operations["submit_ado_api_batches_ado_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Batch */
        get: operations["batch_api_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run */
        get: operations["run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_api_runs__run_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiments */
        get: operations["experiments_api_experiments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Batch */
        post: operations["cancel_batch_api_batches__batch_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdoBatchAccepted */
        AdoBatchAccepted: {
            /** Batch Id */
            batch_id: string;
            /** Imported */
            imported: number;
        };
        /** AgentConfig */
        AgentConfig: {
            /** Name */
            name: string;
            /** Model Tier */
            model_tier: string;
            /** Config Hash */
            config_hash: string;
            /** Resolved Model */
            resolved_model: string;
        };
        /** BatchAccepted */
        BatchAccepted: {
            /** Batch Id */
            batch_id: string;
        };
        /** BatchDetail */
        BatchDetail: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Label */
            label: string;
            /** Source Kind */
            source_kind: string;
            /** Finding Count */
            finding_count: number;
            /** Created At */
            created_at: string;
            /** Budget */
            budget: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /** Verdict Counts */
            verdict_counts: {
                [key: string]: number;
            };
        };
        /** BatchSummary */
        BatchSummary: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Label */
            label: string;
            /** Source Kind */
            source_kind: string;
            /** Finding Count */
            finding_count: number;
            /** Created At */
            created_at: string;
        };
        /** Bin */
        Bin: {
            /** Lower */
            lower: number;
            /** Upper */
            upper: number;
            /** Count */
            count: number;
        };
        /** CancelResponse */
        CancelResponse: {
            /** Status */
            status: string;
        };
        /** ConfigResponse */
        ConfigResponse: {
            /** Model Mode */
            model_mode: string;
            /** Agents */
            agents: components["schemas"]["AgentConfig"][];
        };
        /** Distribution */
        Distribution: {
            /** Count */
            count: number;
            /** Population */
            population: number;
            /** Coverage */
            coverage: number | null;
            /** Mean */
            mean?: number | null;
            /** P50 */
            p50?: number | null;
            /** P95 */
            p95?: number | null;
            /** Maximum */
            maximum?: number | null;
            /** Bins */
            bins?: components["schemas"]["Bin"][];
        };
        /** ExperimentCase */
        ExperimentCase: {
            /** Case Name */
            case_name: string;
            /** Repetition */
            repetition: number;
            /** Passed */
            passed: boolean;
            /** Scores */
            scores: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Cost Usd */
            cost_usd: number | null;
            /** Latency S */
            latency_s: number | null;
        };
        /** ExperimentDetail */
        ExperimentDetail: {
            /** Id */
            id: string;
            /** Agent */
            agent: string;
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Cases */
            cases: components["schemas"]["ExperimentCase"][];
        };
        /** ExperimentSummary */
        ExperimentSummary: {
            /** Id */
            id: string;
            /** Agent */
            agent: string;
            /** Dataset */
            dataset: string;
            /** Dataset Version */
            dataset_version: string;
            /** Git Sha */
            git_sha: string;
            /** Overlay */
            overlay: string;
            /** Repetitions */
            repetitions: number;
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Config Hash */
            config_hash: string;
            /** Git Dirty */
            git_dirty: boolean;
            /** Model Name */
            model_name: string;
            /** Backend */
            backend: string;
            /** Pricing */
            pricing: string;
            /** Harness Version */
            harness_version: string;
            /** Created At */
            created_at: string;
        };
        /**
         * FindingInput
         * @description The published generic JSON schema an external process submits (D1).
         *
         *     Only ``repo_url`` and ``title`` are required; anything missing is extracted from
         *     ``description`` by the intake agent or the finding is parked as ``needs_info``.
         */
        FindingInput: {
            /**
             * External Id
             * @description ID in the originating system
             */
            external_id?: string | null;
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Repo Url
             * @description Git URL or a local path visible to the worker
             */
            repo_url: string;
            /**
             * Revision
             * @description Commit SHA, tag, or branch
             * @default HEAD
             */
            revision: string;
            /** @description Explicit source identity mode; omitted for backwards-compatible inference */
            source_mode?: components["schemas"]["SourceMode"] | null;
            /** File Path */
            file_path?: string | null;
            /** Start Line */
            start_line?: number | null;
            /** End Line */
            end_line?: number | null;
            /** Symbol */
            symbol?: string | null;
            /**
             * Cwe
             * @description e.g. CWE-89
             */
            cwe?: string | null;
            /** @default unknown */
            severity: components["schemas"]["Severity"];
            /** Source Tool */
            source_tool?: string | null;
            /** @default generic_json */
            source_kind: components["schemas"]["FindingSourceKind"];
            /** Ado Work Item Id */
            ado_work_item_id?: number | null;
        };
        /**
         * FindingSourceKind
         * @enum {string}
         */
        FindingSourceKind: "generic_json" | "ado" | "free_text";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** InvocationRecord */
        InvocationRecord: {
            /** Agent */
            agent: string;
            /** Model Name */
            model_name: string;
            /** Config Hash */
            config_hash: string;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cache Read Tokens */
            cache_read_tokens: number;
            /** Cache Write Tokens */
            cache_write_tokens: number;
            /** Cost Usd */
            cost_usd: number | null;
            /** Cost Estimated */
            cost_estimated: boolean;
            /** Latency S */
            latency_s: number;
            /** Requests */
            requests: number;
            /** Repeated Tool Calls */
            repeated_tool_calls: {
                [key: string]: number;
            };
            /** Tools Called */
            tools_called: string[];
            /** Skills Loaded */
            skills_loaded: string[];
        };
        JsonValue: unknown;
        /** MetricsResponse */
        MetricsResponse: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** As Of */
            as_of: string;
            /** Population */
            population: string;
            /** Total Runs */
            total_runs: number;
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /** Verdict Counts */
            verdict_counts: {
                [key: string]: number;
            };
            tokens: components["schemas"]["Distribution"];
            input_tokens: components["schemas"]["Distribution"];
            output_tokens: components["schemas"]["Distribution"];
            cost_usd: components["schemas"]["Distribution"];
            wall_time_s: components["schemas"]["Distribution"];
            agent_time_s: components["schemas"]["Distribution"];
            /** Trends */
            trends: components["schemas"]["TrendPoint"][];
            /** Stages */
            stages: components["schemas"]["StageMetric"][];
            /** Definitions */
            definitions: {
                [key: string]: string;
            };
        };
        /** ReviewRecord */
        ReviewRecord: {
            /**
             * Reviewer
             * @default
             */
            reviewer: string;
            /** Decision */
            decision: string;
            /** Override Label */
            override_label?: string | null;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Created At */
            created_at: string;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /**
             * Reviewer
             * @default
             */
            reviewer: string;
            /** Decision */
            decision: string;
            override_label?: components["schemas"]["VerdictLabel"] | null;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** ReviewSaved */
        ReviewSaved: {
            /** Ok */
            ok: boolean;
        };
        /** RunDetail */
        RunDetail: {
            /** Id */
            id: string;
            /** Batch Id */
            batch_id: string;
            /** Fingerprint */
            fingerprint: string;
            /** Title */
            title: string;
            /** Repo Url */
            repo_url: string;
            /** Revision */
            revision: string;
            /** Cwe */
            cwe: string | null;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
            /** Verdict */
            verdict: string | null;
            /** Confidence */
            confidence: number | null;
            /** Inconclusive Reason */
            inconclusive_reason: string | null;
            /** Priority */
            priority: string | null;
            /** Priority Score */
            priority_score: number | null;
            /** Environment Scope */
            environment_scope: string;
            /** Early Exit */
            early_exit: string | null;
            /** Cost Usd */
            cost_usd: number | null;
            /** Total Tokens */
            total_tokens: number;
            /** Cache Read Tokens */
            cache_read_tokens: number;
            /** Latency S */
            latency_s: number;
            /** Created At */
            created_at: string;
            telemetry: components["schemas"]["RunTelemetry"] | null;
            /** Phase */
            phase: string;
            /** Evidence */
            evidence: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Events */
            events: components["schemas"]["RunEvent"][];
            /** Review History */
            review_history: components["schemas"]["ReviewRecord"][];
            /** Finding */
            finding: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Result */
            result: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Invocations */
            invocations: components["schemas"]["InvocationRecord"][];
            review: components["schemas"]["ReviewRecord"] | null;
        };
        /** RunEvent */
        RunEvent: {
            /** Id */
            id: string;
            /** Phase */
            phase: string;
            /** Detail */
            detail: string;
            /** Created At */
            created_at: string;
        };
        /** RunPage */
        RunPage: {
            /** Items */
            items: components["schemas"]["RunSummary"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** As Of */
            as_of: string;
        };
        /** RunSummary */
        RunSummary: {
            /** Id */
            id: string;
            /** Batch Id */
            batch_id: string;
            /** Fingerprint */
            fingerprint: string;
            /** Title */
            title: string;
            /** Repo Url */
            repo_url: string;
            /** Revision */
            revision: string;
            /** Cwe */
            cwe: string | null;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
            /** Verdict */
            verdict: string | null;
            /** Confidence */
            confidence: number | null;
            /** Inconclusive Reason */
            inconclusive_reason: string | null;
            /** Priority */
            priority: string | null;
            /** Priority Score */
            priority_score: number | null;
            /** Environment Scope */
            environment_scope: string;
            /** Early Exit */
            early_exit: string | null;
            /** Cost Usd */
            cost_usd: number | null;
            /** Total Tokens */
            total_tokens: number;
            /** Cache Read Tokens */
            cache_read_tokens: number;
            /** Latency S */
            latency_s: number;
            /** Created At */
            created_at: string;
            telemetry: components["schemas"]["RunTelemetry"] | null;
            /** Phase */
            phase: string;
        };
        /** RunTelemetry */
        RunTelemetry: {
            /** Schema Version */
            schema_version?: number | null;
            /** Phase */
            phase?: string | null;
            /** Accepted At */
            accepted_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Wall Time S */
            wall_time_s?: number | null;
            /** Agent Time S */
            agent_time_s?: number | null;
            /** Cost Usd */
            cost_usd?: number | null;
            /** Known Cost Usd */
            known_cost_usd?: number | null;
            /** Accounting Complete */
            accounting_complete?: boolean | null;
            /** Cost Accounting Complete */
            cost_accounting_complete?: boolean | null;
            /** Known Tokens */
            known_tokens?: number | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Cost Coverage */
            cost_coverage?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "critical" | "high" | "medium" | "low" | "info" | "unknown";
        /**
         * SourceMode
         * @enum {string}
         */
        SourceMode: "git_revision" | "working_snapshot";
        /** StageMetric */
        StageMetric: {
            /** Agent */
            agent: string;
            /** Invocations */
            invocations: number;
            /** Agent Time S */
            agent_time_s: number;
            /** Tokens */
            tokens: number;
            /** Known Cost Usd */
            known_cost_usd: number;
            /** Cost Coverage */
            cost_coverage: number;
        };
        /** SubmitADORequest */
        SubmitADORequest: {
            /** Work Item Ids */
            work_item_ids: number[];
            /**
             * Label
             * @default
             */
            label: string;
        };
        /** SubmitRequest */
        SubmitRequest: {
            /** Findings */
            findings: components["schemas"]["FindingInput"][];
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Mode
             * @default auto
             * @enum {string}
             */
            mode: "auto" | "local" | "temporal";
        };
        /** TrendPoint */
        TrendPoint: {
            /** Date */
            date: string;
            /** Runs */
            runs: number;
            /** Tokens */
            tokens: number | null;
            /** Cost Usd */
            cost_usd: number | null;
            /** Wall Time S */
            wall_time_s: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerdictLabel
         * @enum {string}
         */
        VerdictLabel: "potentially_exploitable" | "likely_not_exploitable" | "inconclusive";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    run_page_api_run_page_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
                verdict?: string | null;
                population?: ("operational" | "demo" | "legacy") | null;
                metric?: ("total_tokens" | "input_tokens" | "output_tokens" | "cost_usd" | "wall_time_s") | null;
                lower?: number | null;
                upper?: number | null;
                upper_inclusive?: boolean;
                search?: string;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_metrics_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
                population?: "operational" | "demo" | "legacy";
                since?: string | null;
                until?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiment_detail_api_experiments__experiment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batches_api_batches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchSummary"][];
                };
            };
        };
    };
    submit_api_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_ado_api_batches_ado_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitADORequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdoBatchAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_api_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_runs_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
                verdict?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_api_runs__run_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSaved"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiments_api_experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentSummary"][];
                };
            };
        };
    };
    config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    cancel_batch_api_batches__batch_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
