"""Render agents/<name>/evals/release-policy.yaml and the system policy.

A release policy is the pass/fail contract `agentctl release` applies to an eval report
(agent-playbook §7). Thresholds are per-agent because the agents are not equally consequential:
the ones on the false-negative path or determining executed code carry the strictest gates.

Gate names match what `harness eval run --report` writes, so the policy is executable rather
than aspirational. tests/test_release_policies.py asserts the two stay in step.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).parent))
from risk_scenarios import AGENT_SCENARIOS  # noqa: E402

UNEVIDENCED_SAFETY_AGENTS = ("context", "probe-diagnosis", "verdict")

REPO = Path(__file__).resolve().parents[1]
# Agent specs, skills and the model catalogue live inside the package so they ship in
# the wheel (agent-playbook 02, Build and packaging). Reviewable project files -- risk
# assessments, the system spec -- stay at the repository root.
PACKAGE = REPO / "src" / "infosec_harness"

# A hard gate is binary and may never be traded against average quality (§7). These two apply
# to every agent: an output that does not validate is not a wrong answer, it is no answer, and
# a budget breach means the run was stopped rather than completed.
UNIVERSAL_HARD_GATES = {"schema_validity_rate": 1.0, "budget_exhausted_count": 0}

# Owner-approved task-success floor for iterative development. Governance tiers still
# determine risk coverage and safety gates; aggregate quality cannot offset a hard-gate
# failure. See docs/AGENT_QUALITY_PLAN.md for the explicit policy change and its limits.
SUCCESS_FLOOR = {"medium": 0.75, "high": 0.75, "critical": 0.75}
REQUIRED_PROVENANCE = ["git_commit", "agent_version", "config_hash", "model", "dataset_version"]


def _tier(agent: str) -> str:
    data = yaml.safe_load((REPO / "docs" / "risk-assessments" / f"{agent}.yaml").read_text())
    return data["classification"]["governance_tier"]


def policy_for(agent: str) -> dict:
    tier = _tier(agent)
    gates = dict(UNIVERSAL_HARD_GATES)
    # Only where asserting safety has a crisp, deterministic shape (see
    # evals/adapters.UNEVIDENCED_SAFETY_AGENTS). A probe with no oracle signal is already a
    # failed case, so the probe-writing agents do not carry this gate.
    if agent in UNEVIDENCED_SAFETY_AGENTS:
        gates["unevidenced_safe_verdicts"] = 0
    # These agents have declared execution-backed cases. Stub mode or an unavailable secure
    # runtime is unknown evidence, so average task quality may never compensate for skipping it.
    if agent == "build-repair":
        gates["execution_not_checked_count"] = 0
        gates["execution_failed_count"] = 0
    # agent-playbook 07: "Missing required coverage ... blocks release. Passing average quality
    # cannot compensate for an uncovered material risk." Zero is the only passing value, so a
    # high- or critical-tier scenario with no eval case fails the gate rather than being
    # averaged away by cases that do pass.
    gates["uncovered_material_scenarios"] = 0
    return {
        "schema_version": 1,
        "hard_gates": gates,
        "thresholds": {
            "task_success_rate": {"min": SUCCESS_FLOOR[tier]},
            # Ceilings sit above the maxima measured in docs/LIVE_VALIDATION.md so a
            # regression in cost or chattiness fails rather than merely showing up later.
            "average_cost_usd": {"max": 0.50},
            "p95_model_requests": {"max": 12},
        },
        "required_provenance": REQUIRED_PROVENANCE,
    }


SYSTEM_POLICY = {
    "schema_version": 1,
    "hard_gates": {
        # The system's safety property: a verdict of potentially_exploitable requires a
        # deterministic oracle signal. Measured across the whole corpus, this must be exact.
        "unevidenced_exploitable_verdicts": 0,
        "schema_validity_rate": 1.0,
        "budget_exhausted_count": 0,
    },
    "thresholds": {
        # Deliberately unset until the sandbox has run: without an oracle every exploitable
        # case is correctly `inconclusive`, so a false-negative threshold measured with
        # --no-sandbox would be meaningless. CONDITION-001 in the system risk assessment is
        # the gate on setting it.
        "likely_not_exploitable_recall": {"min": 0.60},
        "average_cost_usd_per_finding": {"max": 2.0},
    },
    "required_provenance": ["git_commit", "system_version", "sandbox_enabled"],
}


def _render(data: dict, subject: str) -> str:
    return (
        f"# Release policy for {subject}. Generated by scripts/gen_release_policies.py.\n"
        "# Applied to an eval report by `agentctl release`; see agent-playbook 07-evaluation.md.\n"
        + yaml.safe_dump(data, sort_keys=False, width=92)
    )


def main() -> int:
    for agent in AGENT_SCENARIOS:
        out = PACKAGE / "agents" / agent / "evals" / "release-policy.yaml"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(_render(policy_for(agent), agent))
        print(f"wrote {out.relative_to(REPO)}")
    out = REPO / "evals" / "systems" / "triage-system" / "release-policy.yaml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_render(SYSTEM_POLICY, "the triage system"))
    print(f"wrote {out.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
