"""Render the packaged runtime skill index (src/infosec_harness/skills/README.md).

`scripts/generated.py` writes it and `--check` reports drift, so `just generated-sync` and
`just generated-check` keep it current.
"""

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / "src/infosec_harness/skills"
README = SKILLS / "README.md"


def skills():
    for path in sorted(SKILLS.glob("*/SKILL.md")):
        text = path.read_text(encoding="utf-8")
        header = text[4:].partition("\n---\n")[0]
        description = " ".join(str(yaml.safe_load(header)["description"]).split())
        yield path.parent.name, description, path.stat().st_size


def render():
    rows = list(skills())
    catalog = "\n".join(f"- {name}: {description}" for name, description, _ in rows)
    lines = [
        "# Runtime skills",
        "",
        "Generated by `scripts/skill_catalog.py` (`just generated-sync`); do not edit by hand.",
        "The investigator loads every skill below as a deferred capability: the model sees one",
        "`- name: description` catalog line per skill on every request and loads a body on demand.",
        "Skills hold expertise only; they grant no permissions. `tests/agents/test_skill_catalog.py`",
        "checks frontmatter, required sections, size and the catalog budget.",
        "",
        f"{len(rows)} skills; catalog {len(catalog):,} characters.",
        "",
        "| Skill | Description | Bytes |",
        "|---|---|---:|",
    ]
    for name, description, size in rows:
        lines.append(f"| `{name}` | {description.replace('|', '&#124;')} | {size:,} |")
    return "\n".join(lines) + "\n"
